name: VanillaGenerator
main: muqsit\vanillagenerator\Loader
api: 4.0.0
version: 0.0.1
author: Muqsit
github: https://github.com/Muqsit
twitter: https://twitter.com/muqsitrayyan
forum: https://forums.pmmp.io/members/muqsit.25/
hotel: trivago